package com.cognizant.springlearn;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Default Spring Boot smoke test generated by Spring Initializr.
 * Verifies that the Spring ApplicationContext loads successfully.
 */
@SpringBootTest
class SpringLearnApplicationTests {

    @Test
    void contextLoads() {
        // Intentionally empty - if the ApplicationContext fails to
        // start, this test will fail automatically.
    }
}
