import java.util.List;

/**
 * OrmLearnApplication
 * -------------------
 * Equivalent of the Spring Boot main class generated by Spring Initializr
 * (group=com.cognizant, artifact=orm-learn).
 *
 * @SpringBootApplication marks this as the bootstrap class.
 * SpringApplication.run() builds the ApplicationContext (our simulation of
 * component scanning + bean creation), and we manually register the beans
 * that a real @ComponentScan would have discovered automatically.
 */
@SpringBootApplication
public class OrmLearnApplication {

    private static final Logger LOGGER = LoggerFactory.getLogger(OrmLearnApplication.class);

    private static CountryService countryService;

    public static void main(String[] args) {
        ApplicationContext context = SpringApplication.run(OrmLearnApplication.class, args);
        LOGGER.info("Inside main");

        // Seed the "country" table the same way the MySQL script in sql/schema.sql does:
        //   insert into country values ('IN', 'India');
        //   insert into country values ('US', 'United States of America');
        CountryRepository countryRepository = context.registerRepository(CountryRepository.class);
        countryRepository.save(new Country("IN", "India"));
        countryRepository.save(new Country("US", "United States of America"));

        countryService = context.registerBean(new CountryService());

        testGetAllCountries();
    }

    private static void testGetAllCountries() {
        LOGGER.info("Start");
        List<Country> countries = countryService.getAllCountries();
        LOGGER.debug("countries={}", countries);
        LOGGER.info("End");
    }
}
